# Winapps
windowrule = float on, match:class ^(.*Microsoft.*)$
windowrule = fullscreen_state 0 0, match:class ^(.*Microsoft.*)$
windowrule = persistent_size on, match:class ^(.*Microsoft.*)$
# windowrule = size 10 10, match:title ^()$
